# Generated by Django 4.1.5 on 2023-02-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="author's name", max_length=30, verbose_name="author's first name")),
                ('last_name', models.CharField(help_text="author's last name", max_length=30, verbose_name="author's last name")),
                ('date_of_birth', models.DateField(blank=True, help_text='date of birthday', null=True, verbose_name='date of birthday')),
                ('date_of_death', models.DateField(blank=True, help_text='date of death', null=True, verbose_name='date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Book's title", max_length=50, verbose_name="book's title")),
                ('summary', models.TextField(help_text='short discription', max_length=1000, verbose_name='discription')),
                ('isbn', models.CharField(help_text='13 symbols', max_length=13, verbose_name='ISBN')),
                ('author', models.ManyToManyField(help_text='choose an author', null=True, to='catalog.author', verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='choose a genre', max_length=20, verbose_name='genres')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='choose a language', max_length=20, verbose_name='language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='status', max_length=20, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='inventory number', max_length=20, null=True, verbose_name='inventory number')),
                ('imprint', models.CharField(help_text='edition', max_length=200, verbose_name='edition')),
                ('due_back', models.DateField(blank=True, help_text='end term in this status', null=True, verbose_name='Date of status end')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='change status of instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='choose a genre', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='choose a language', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language'),
        ),
    ]
