# Generated by Django 4.1.5 on 2023-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='choose an author', to='catalog.author', verbose_name='author'),
        ),
    ]
